/*
 * PRG32 BOUNCE: a small RGB565 sprite and input-state example.
 *
 * The title screen deliberately uses the 320x200 game splash helper, so it
 * remains inside the game viewport on both the board and QEMU.
 */
#include "prg32.h"

#define BALL_SIZE 24
#define BACKGROUND 0x0011
#define OUTLINE 0x0000
#define LIGHT 0xffff
#define RED 0xf800
#define BLUE 0x001f

/* The dark-blue pixels are the sprite background and match BACKGROUND. */
static const uint16_t prg32_bounce_ball[BALL_SIZE * BALL_SIZE] = {
    BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,OUTLINE,OUTLINE,OUTLINE,OUTLINE,OUTLINE,OUTLINE,OUTLINE,OUTLINE,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,
    BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,OUTLINE,OUTLINE,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,OUTLINE,OUTLINE,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,
    BACKGROUND,BACKGROUND,BACKGROUND,OUTLINE,OUTLINE,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,RED,RED,RED,RED,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,OUTLINE,OUTLINE,BACKGROUND,BACKGROUND,
    BACKGROUND,BACKGROUND,OUTLINE,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,RED,RED,RED,RED,RED,RED,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,OUTLINE,BACKGROUND,
    BACKGROUND,OUTLINE,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,RED,RED,RED,RED,RED,RED,RED,RED,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,OUTLINE,
    BACKGROUND,OUTLINE,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,RED,RED,RED,BLUE,BLUE,BLUE,BLUE,RED,RED,RED,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,OUTLINE,
    BACKGROUND,OUTLINE,LIGHT,LIGHT,LIGHT,LIGHT,RED,RED,RED,BLUE,LIGHT,LIGHT,LIGHT,BLUE,RED,RED,RED,RED,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,OUTLINE,
    BACKGROUND,OUTLINE,LIGHT,LIGHT,LIGHT,RED,RED,RED,RED,BLUE,LIGHT,BLUE,BLUE,BLUE,RED,RED,RED,RED,RED,LIGHT,LIGHT,LIGHT,LIGHT,OUTLINE,
    OUTLINE,LIGHT,LIGHT,LIGHT,LIGHT,RED,RED,RED,RED,BLUE,LIGHT,LIGHT,BLUE,BLUE,RED,RED,RED,RED,RED,LIGHT,LIGHT,LIGHT,LIGHT,OUTLINE,
    OUTLINE,LIGHT,LIGHT,LIGHT,RED,RED,RED,RED,RED,BLUE,LIGHT,LIGHT,BLUE,BLUE,RED,RED,RED,RED,RED,RED,LIGHT,LIGHT,LIGHT,OUTLINE,
    OUTLINE,LIGHT,LIGHT,LIGHT,RED,RED,RED,RED,RED,BLUE,BLUE,BLUE,BLUE,BLUE,RED,RED,RED,RED,RED,RED,LIGHT,LIGHT,LIGHT,OUTLINE,
    OUTLINE,LIGHT,LIGHT,LIGHT,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,LIGHT,LIGHT,LIGHT,OUTLINE,
    OUTLINE,LIGHT,LIGHT,LIGHT,LIGHT,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,LIGHT,LIGHT,LIGHT,LIGHT,OUTLINE,
    OUTLINE,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,RED,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,OUTLINE,
    BACKGROUND,OUTLINE,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,RED,RED,RED,LIGHT,LIGHT,LIGHT,LIGHT,RED,RED,RED,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,OUTLINE,
    BACKGROUND,OUTLINE,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,RED,RED,LIGHT,LIGHT,LIGHT,LIGHT,RED,RED,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,OUTLINE,
    BACKGROUND,OUTLINE,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,RED,RED,RED,RED,RED,RED,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,OUTLINE,
    BACKGROUND,BACKGROUND,OUTLINE,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,OUTLINE,BACKGROUND,
    BACKGROUND,BACKGROUND,BACKGROUND,OUTLINE,OUTLINE,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,OUTLINE,OUTLINE,BACKGROUND,BACKGROUND,
    BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,OUTLINE,OUTLINE,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,LIGHT,OUTLINE,OUTLINE,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,
    BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,OUTLINE,OUTLINE,OUTLINE,OUTLINE,OUTLINE,OUTLINE,OUTLINE,OUTLINE,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,
    BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,
    BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,
    BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND,BACKGROUND
};

static int ball_x;
static int ball_y;
static int ball_dx;
static int ball_dy;
static int started;
static uint32_t previous_input;

void prg32_bounce_c_init(void) {
    ball_x = 148;
    ball_y = 88;
    ball_dx = 2;
    ball_dy = 2;
    started = 0;
    previous_input = 0;
}

void prg32_bounce_c_update(void) {
    uint32_t input = prg32_input_read();
    uint32_t pressed = input & ~previous_input;
    previous_input = input;

    if (!started) {
        if (pressed & PRG32_BTN_START) {
            started = 1;
            prg32_buzzer_tone(660, 60, 512);
        }
        return;
    }

    ball_x += ball_dx;
    ball_y += ball_dy;
    if (ball_x <= 0 || ball_x >= PRG32_GAME_W - BALL_SIZE) {
        ball_dx = -ball_dx;
        ball_x += ball_dx;
    }
    if (ball_y <= 0 || ball_y >= PRG32_GAME_H - BALL_SIZE) {
        ball_dy = -ball_dy;
        ball_y += ball_dy;
    }
}

void prg32_bounce_c_draw(void) {
    if (!started) {
        prg32_splash_draw_game("PRG32 BOUNCE", "PRESS START", BACKGROUND,
                               PRG32_COLOR_WHITE, RED);
        return;
    }

    prg32_gfx_clear(BACKGROUND);
    prg32_gfx_text8(8, 8, "PRG32", PRG32_COLOR_WHITE, BACKGROUND);
    prg32_sprite_draw_24x24(ball_x, ball_y, prg32_bounce_ball);
}
