from __future__ import annotations

import argparse
import importlib.util
from pathlib import Path
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[1]
TOOL_PATH = ROOT / "tools" / "prg32_game.py"


def load_tool():
    spec = importlib.util.spec_from_file_location("prg32_game", TOOL_PATH)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot import {TOOL_PATH}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


prg32_game = load_tool()


class PartitionParsingTests(unittest.TestCase):
    def test_parse_partition_size_units(self) -> None:
        self.assertEqual(prg32_game.parse_partition_size("512K"), 512 * 1024)
        self.assertEqual(prg32_game.parse_partition_size("2M"), 2 * 1024 * 1024)
        self.assertEqual(prg32_game.parse_partition_size("0x210000"), 0x210000)

    def test_read_partition_slot(self) -> None:
        offset, size = prg32_game.read_partition_slot(
            ROOT / "partitions_prg32.csv",
            "cart0",
        )
        self.assertEqual(offset, 0x210000)
        self.assertEqual(size, 512 * 1024)


class SymbolParsingTests(unittest.TestCase):
    def test_parse_nm_ignores_non_symbol_lines(self) -> None:
        symbols = prg32_game.parse_nm(
            """
00000000 T prg32_ticks_ms
not-a-symbol
00000010 D prg32_cart_exec
"""
        )
        self.assertEqual(symbols["prg32_ticks_ms"], 0)
        self.assertEqual(symbols["prg32_cart_exec"], 0x10)

    def test_write_imports_emits_all_imports(self) -> None:
        imports = {
            name: 0x40000000 + index * 4
            for index, name in enumerate(prg32_game.IMPORT_NAMES)
        }
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "imports.ld"
            prg32_game.write_imports(path, imports)
            text = path.read_text(encoding="utf-8")

        self.assertIn("Generated by tools/prg32_game.py", text)
        self.assertIn("PROVIDE(prg32_ticks_ms = 0x40000000);", text)
        self.assertIn("PROVIDE(prg32_score_submit =", text)

    def test_imports_include_platform_tile_helpers(self) -> None:
        self.assertIn("prg32_playfield_draw_dual", prg32_game.IMPORT_NAMES)
        self.assertIn("prg32_platform_actor_step", prg32_game.IMPORT_NAMES)
        self.assertIn("prg32_platform_camera_follow", prg32_game.IMPORT_NAMES)

    def test_imports_include_audio_plus_helpers(self) -> None:
        self.assertIn("prg32_audio_play_sample_pan", prg32_game.IMPORT_NAMES)
        self.assertIn("prg32_audio_note_on_pan", prg32_game.IMPORT_NAMES)
        self.assertIn("prg32_audio_get_mode", prg32_game.IMPORT_NAMES)

    def test_imports_include_splash_helpers(self) -> None:
        self.assertIn("prg32_splash_draw", prg32_game.IMPORT_NAMES)
        self.assertIn("prg32_splash_show", prg32_game.IMPORT_NAMES)
        self.assertIn("prg32_splash_show_default", prg32_game.IMPORT_NAMES)

    def test_detect_entries_accepts_c_prefix(self) -> None:
        entries = prg32_game.detect_entries(
            {
                "platformer_c_init": 0,
                "platformer_c_update": 4,
                "platformer_c_draw": 8,
            },
            "platformer_c",
        )
        self.assertEqual(
            entries,
            ("platformer_c_init", "platformer_c_update", "platformer_c_draw"),
        )


class QemuUploadTests(unittest.TestCase):
    def test_upload_qemu_stages_cartridge_at_partition_offset(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            flash = tmp_path / "qemu_flash.bin"
            cart = tmp_path / "game.prg32"
            partitions = tmp_path / "partitions.csv"

            flash.write_bytes(b"\x00" * 64)
            cart.write_bytes(b"PRG2")
            partitions.write_text(
                "cart0, data, 0x40, 0x10, 8,\n",
                encoding="utf-8",
            )

            args = argparse.Namespace(
                flash=str(flash),
                cartridge=str(cart),
                partitions=str(partitions),
                slot="cart0",
            )
            prg32_game.upload_qemu(args)

            data = flash.read_bytes()
            self.assertEqual(data[0x10:0x14], b"PRG2")
            self.assertEqual(data[0x14:0x18], b"\xff" * 4)


class DoctorTests(unittest.TestCase):
    def test_host_only_doctor_does_not_require_esp_idf(self) -> None:
        rc = prg32_game.main(["doctor", "--host-only"])
        self.assertEqual(rc, 0)


if __name__ == "__main__":
    unittest.main()
