from __future__ import annotations

import argparse
import io
from pathlib import Path
import contextlib
import tempfile
import unittest

from prg32.utilities import partition_handler, runtime_handler, env_variables
from prg32.cartridge import build_cartridge
from prg32.store import metadata as store_metadata
from prg32.qemu import upload_qemu
from prg32.utilities.environment_check import doctor
from prg32.abi.abi_generated import (
    ABI_HASH,
    COMPATIBLE_ABI_HASHES,
    FEATURE_BITS,
    IMPORT_NAMES,
)
from prg32.prg32 import main as prg32_main

ROOT = Path(__file__).resolve().parents[1]

class PartitionParsingTests(unittest.TestCase):
    def test_parse_partition_size_units(self) -> None:
        self.assertEqual(partition_handler.parse_partition_size("512K"), 512 * 1024)
        self.assertEqual(partition_handler.parse_partition_size("2M"), 2 * 1024 * 1024)
        self.assertEqual(partition_handler.parse_partition_size("0x210000"), 0x210000)

    def test_read_partition_slot(self) -> None:
        offset, size = partition_handler.read_partition_slot(
            ROOT / "partitions_prg32.csv",
            "cart0",
        )
        self.assertEqual(offset, 0x210000)
        self.assertEqual(size, 128 * 1024)

class SymbolParsingTests(unittest.TestCase):
    def test_parse_nm_ignores_non_symbol_lines(self) -> None:
        symbols = runtime_handler.parse_nm(
            """
00000000 T prg32_ticks_ms
not-a-symbol
00000010 D prg32_cart_exec
"""
        )
        self.assertEqual(symbols["prg32_ticks_ms"], 0)
        self.assertEqual(symbols["prg32_cart_exec"], 0x10)

    def test_write_imports_emits_all_imports(self) -> None:
        imports = {
            name: 0x40000000 + index * 4
            for index, name in enumerate(IMPORT_NAMES)
        }
        with tempfile.TemporaryDirectory() as tmp:
            path = Path(tmp) / "imports.ld"
            build_cartridge.write_imports(path, imports)
            text = path.read_text(encoding="utf-8")

        self.assertIn("Generated by prg32.", text)
        self.assertIn("PROVIDE(prg32_ticks_ms = 0x40000000);", text)
        self.assertIn("PROVIDE(prg32_score_submit =", text)

    def test_imports_include_platform_tile_helpers(self) -> None:
        self.assertIn("prg32_playfield_draw_dual", IMPORT_NAMES)
        self.assertIn("prg32_platform_actor_step", IMPORT_NAMES)
        self.assertIn("prg32_platform_camera_follow", IMPORT_NAMES)

    def test_imports_include_audio_plus_helpers(self) -> None:
        self.assertIn("prg32_audio_play_sample_pan", IMPORT_NAMES)
        self.assertIn("prg32_audio_note_on_pan", IMPORT_NAMES)
        self.assertIn("prg32_audio_get_mode", IMPORT_NAMES)

    def test_imports_include_splash_helpers(self) -> None:
        self.assertIn("prg32_splash_draw", IMPORT_NAMES)
        self.assertIn("prg32_splash_show", IMPORT_NAMES)
        self.assertIn("prg32_splash_show_default", IMPORT_NAMES)

    def test_detect_entries_accepts_c_prefix(self) -> None:
        entries = build_cartridge.detect_entries(
            {
                "platformer_c_init": 0,
                "platformer_c_update": 4,
                "platformer_c_draw": 8,
            },
            "platformer_c",
        )
        self.assertEqual(
            entries,
            ("platformer_c_init", "platformer_c_update", "platformer_c_draw"),
        )

class PortableHeaderTests(unittest.TestCase):
    def test_current_runtime_accepts_previous_append_only_abi_hash(self) -> None:
        self.assertIn(0xEC21EFE2, COMPATIBLE_ABI_HASHES)
        self.assertIn(0x5626CB8A, COMPATIBLE_ABI_HASHES)
        payload = b"\0\0\0\0"
        header = env_variables.CART_HEADER_V2.pack(
            env_variables.CART_MAGIC,
            env_variables.CART_ABI_MAJOR,
            1,
            env_variables.CART_HEADER_V2.size,
            env_variables.PRG32_CART_FLAG_ABI_TABLE,
            env_variables.FALLBACK_CART_LOAD_ADDR,
            len(payload), len(payload), 0, 0, 0, 0,
            b"old" + b"\0" * 29,
            0xEC21EFE2,
            0, 0, 0, 0, 0,
            env_variables.PRG32_IMPORT_MODEL_ABI_TABLE,
        )
        runtime_handler.validate_cartridge_contract(header + payload)

    def test_performance_abi_is_appended_after_indexed_graphics(self) -> None:
        self.assertEqual(IMPORT_NAMES[122], "prg32_sprite_draw_indexed")
        self.assertEqual(IMPORT_NAMES[123], "prg32_sprite_draw_bitplanes")
        self.assertEqual(
            IMPORT_NAMES[124:],
            [
                "prg32_perf_now_us", "prg32_perf_begin",
                "prg32_perf_case_begin", "prg32_perf_record",
                "prg32_perf_case_end", "prg32_perf_end",
                "prg32_perf_abort", "prg32_perf_get_state",
                "prg32_perf_get_summary",
            ],
        )

    def test_portable_build_uses_position_tolerant_riscv_flags(self) -> None:
        # We look in build_cartridge.py now
        TOOL_PATH = ROOT / "prg32" / "cartridge" / "build_cartridge.py"
        text = TOOL_PATH.read_text(encoding="utf-8")

        self.assertIn('"-mcmodel=medany"', text)
        self.assertIn('"-msmall-data-limit=0"', text)

    def test_v2_header_records_abi_table_import_model(self) -> None:
        header = env_variables.CART_HEADER_V2.pack(
            env_variables.CART_MAGIC,
            env_variables.CART_ABI_MAJOR,
            env_variables.CART_ABI_MINOR,
            env_variables.CART_HEADER_V2.size,
            env_variables.PRG32_CART_FLAG_ABI_TABLE,
            env_variables.FALLBACK_CART_LOAD_ADDR,
            4,
            4,
            0,
            0,
            0,
            0,
            b"test" + b"\0" * 28,
            ABI_HASH,
            FEATURE_BITS["audio"],
            FEATURE_BITS["sprites"],
            0,
            0,
            0,
            env_variables.PRG32_IMPORT_MODEL_ABI_TABLE,
        )
        with tempfile.TemporaryDirectory() as tmp:
            cart = Path(tmp) / "portable.prg32"
            cart.write_bytes(header + b"\0\0\0\0")
            buf = io.StringIO()
            args = argparse.Namespace(cartridge=str(cart))
            with contextlib.redirect_stdout(buf):
                store_metadata.inspect_metadata(args)
        text = buf.getvalue()
        self.assertIn('"import_model": "abi-table"', text)
        self.assertIn(f'"abi_hash": "0x{ABI_HASH:08x}"', text)


class QemuUploadTests(unittest.TestCase):
    def test_upload_qemu_stages_cartridge_at_partition_offset(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            tmp_path = Path(tmp)
            flash = tmp_path / "qemu_flash.bin"
            cart = tmp_path / "game.prg32"
            partitions = tmp_path / "partitions.csv"

            payload = b"\0\0\0\0"
            header = env_variables.CART_HEADER_V2.pack(
                env_variables.CART_MAGIC,
                env_variables.CART_ABI_MAJOR,
                env_variables.CART_ABI_MINOR,
                env_variables.CART_HEADER_V2.size,
                env_variables.PRG32_CART_FLAG_ABI_TABLE,
                env_variables.FALLBACK_CART_LOAD_ADDR,
                len(payload),
                len(payload),
                0,
                0,
                0,
                0,
                b"test" + b"\0" * 28,
                ABI_HASH,
                0,
                0,
                0,
                0,
                0,
                env_variables.PRG32_IMPORT_MODEL_ABI_TABLE,
            )
            flash.write_bytes(b"\x00" * 256)
            cart.write_bytes(header + payload)
            partitions.write_text(
                "cart0, data, 0x40, 0x10, 128,\n",
                encoding="utf-8",
            )

            args = argparse.Namespace(
                flash=str(flash),
                cartridge=str(cart),
                partitions=str(partitions),
                slot="cart0",
            )
            upload_qemu.upload_qemu(args)

            data = flash.read_bytes()
            self.assertEqual(data[0x10:0x14], b"PRG2")
            erased = data[0x10 + len(header) + len(payload):0x10 + 128]
            self.assertEqual(erased, b"\xff" * len(erased))


class DoctorTests(unittest.TestCase):
    def test_host_only_doctor_does_not_require_esp_idf(self) -> None:
        rc = prg32_main(["doctor", "--host-only", "--partitions", str(ROOT / "partitions_prg32.csv")])
        self.assertEqual(rc, 0)


if __name__ == "__main__":
    unittest.main()
