from pathlib import Path
import argparse
import subprocess
import os
import sys
import binascii
import struct
import tempfile

from prg32.utilities.logging import *
from prg32.utilities.env_variables import *
from prg32.utilities.runtime_handler import fetch_runtime, runtime_from_elf, parse_nm, run
from prg32.abi.abi_generated import ABI_HASH, ABI_MAJOR, ABI_MINOR, FEATURE_BITS, IMPORT_NAMES
def write_linker(path: Path, load_addr: int, init_symbol: str) -> None:
    path.write_text(
        f"""/* Generated by prg32. */
OUTPUT_ARCH(riscv)
ENTRY({init_symbol})

SECTIONS
{{
    . = 0x{load_addr:08x};
    __cart_start = .;

    .text : {{
        *(.text*)
    }}

    .rodata : {{
        *(.rodata*)
    }}

    . = ALIGN(4);
    .data : {{
        *(.data*)
        *(.sdata*)
    }}

    . = ALIGN(4);
    __cart_load_end = .;

    .bss (NOLOAD) : {{
        *(.bss*)
        *(.sbss*)
        *(COMMON)
    }}

    . = ALIGN(4);
    __cart_end = .;

    /DISCARD/ : {{
        *(.comment*)
        *(.riscv.attributes*)
        *(.note*)
    }}
}}
""",
        encoding="utf-8",
    )

def write_imports(path: Path, imports: dict[str, int]) -> None:
    lines = ["/* Generated by prg32. */"]
    for name in IMPORT_NAMES:
        if name not in imports:
            raise SystemExit(f"runtime import missing: {name}")
        lines.append(f"PROVIDE({name} = 0x{int(imports[name]):08x});")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")

def detect_entries(symbols: dict[str, int], prefix: str | None) -> tuple[str, str, str]:
    if prefix:
        entries = (f"{prefix}_init", f"{prefix}_update", f"{prefix}_draw")
        missing = [name for name in entries if name not in symbols]
        if missing:
            raise SystemExit("game ELF is missing entries: " + ", ".join(missing))
        return entries

    def one_suffix(suffix: str) -> str:
        matches = sorted(
            name for name in symbols
            if name.endswith(suffix) and not name.startswith("__cart_")
        )
        if len(matches) != 1:
            raise SystemExit(
                f"could not infer a unique {suffix} entry; pass --entry-prefix"
            )
        return matches[0]

    return (one_suffix("_init"), one_suffix("_update"), one_suffix("_draw"))

def write_portable_stubs(path: Path,
                         init_sym: str,
                         update_sym: str,
                         draw_sym: str) -> None:
    lines = [
        "/* Generated by prg32 for one portable cartridge build. */",
        ".section .data.__prg32_abi,\"aw\",@progbits",
        ".globl __prg32_abi",
        ".align 2",
        "__prg32_abi:",
        "    .word 0",
        ".section .text.prg32_abi_stubs,\"ax\",@progbits",
        ".option push",
        ".option norelax",
    ]
    for index, name in enumerate(IMPORT_NAMES):
        offset = 20 + index * 4
        lines.extend([
            f".globl {name}",
            f"{name}:",
            "    la t0, __prg32_abi",
            "    lw t0, 0(t0)",
            f"    lw t1, {offset}(t0)",
            "    jr t1",
        ])
    for entry_name, target in (
        ("prg32_entry_init", init_sym),
        ("prg32_entry_update", update_sym),
        ("prg32_entry_draw", draw_sym),
    ):
        lines.extend([
            f".globl {entry_name}",
            f"{entry_name}:",
            "    addi sp, sp, -16",
            "    sw ra, 12(sp)",
            "    la t0, __prg32_abi",
            "    sw a0, 0(t0)",
            f"    call {target}",
            "    lw ra, 12(sp)",
            "    addi sp, sp, 16",
            "    ret",
        ])
    lines.extend([".option pop", ""])
    path.write_text("\n".join(lines), encoding="utf-8")

def feature_mask(names: list[str]) -> int:
    mask = 0
    for name in names:
        key = name.lower().replace("-", "_")
        if key not in FEATURE_BITS:
            raise SystemExit(
                f"unknown feature {name!r}; choices: {', '.join(sorted(FEATURE_BITS))}"
            )
        mask |= int(FEATURE_BITS[key])
    return mask

def build_cartridge_core(source: str, 
                         out: str,
                         entry_prefix: str,
                         tool_prefix : str,
                         march : str,
                         mabi: str,
                         portable: bool = True,
                         legacy_absolute_imports: bool = False,
                         required_features: list[str] = [],
                         optional_features: list[str] = [],
                         multiplayer: bool = False,
                         audio_block : str | None = None,
                         runtime_url: str | None = None,
                         firmware_elf : str | None = None,
                         name: str | None = None) -> None:
    
    if portable and legacy_absolute_imports:
        raise SystemExit("--portable and --legacy-absolute-imports are mutually exclusive")
    
    if portable:
        runtime = {
            "cart_load_addr": 0x40800000,
            "cart_ram_size": FALLBACK_CART_RAM_SIZE,
            "cart_max_size": 128 * 1024,
            "imports": {},
        }
    elif runtime_url:
        runtime = fetch_runtime(runtime_url)
    elif firmware_elf:
        runtime = runtime_from_elf(Path(firmware_elf), tool_prefix)
    else:
        raise SystemExit("build requires --portable, --runtime-url, or --firmware-elf")

    load_addr = int(runtime["cart_load_addr"])
    if "cart_ram_size" not in runtime:
        print(
            "warning: runtime did not report cart_ram_size; "
            f"using fallback {FALLBACK_CART_RAM_SIZE} bytes",
            file=sys.stderr,
        )
    ram_size = int(runtime.get("cart_ram_size", FALLBACK_CART_RAM_SIZE))
    imports = {k: int(v) for k, v in runtime.get("imports", {}).items()}
    req_features = feature_mask(required_features)
    opt_features = feature_mask(optional_features)

    source = Path(source)
    out = Path(out)
    name = name or source.parent.parent.name or source.stem
    name_bytes = name.encode("ascii", "replace")[:31]

    with tempfile.TemporaryDirectory(prefix="prg32-cart-") as tmp_s:
        tmp = Path(tmp_s)
        obj = tmp / "game.o"
        elf = tmp / "game.elf"
        raw = tmp / "game.bin"
        imports_ld = tmp / "imports.ld"
        linker_ld = tmp / "cart.ld"
        stubs_s = tmp / "portable_stubs.S"
        stubs_o = tmp / "portable_stubs.o"

        compile_cmd = [
            tool_prefix + "gcc",
            "-march=" + march,
            "-mabi=" + mabi,
            "-I", str(ROOT_DIR / "components/prg32/include"),
            "-I", str(ROOT_DIR / "components/prg32_audio/include"),
            "-I", str(ROOT_DIR / "main"),
            "-c", str(source),
            "-o", str(obj),
        ]
        if source.suffix.lower() == ".c":
            compile_cmd[1:1] = [
                "-std=c99",
                "-ffreestanding",
                "-fno-builtin",
                "-Os",
            ]
            if portable:
                compile_cmd[1:1] = [
                    "-mcmodel=medany",
                    "-msmall-data-limit=0",
                    # QEMU and hardware may place the executable buffer at a
                    # different address. Avoid compiler-generated absolute
                    # switch/pointer tables until relocation records are part
                    # of the portable package format.
                    "-fno-jump-tables",
                    "-fno-tree-switch-conversion",
                ]
        else:
            compile_cmd[1:1] = ["-x", "assembler-with-cpp"]

        # Compile once so nm can infer the entry prefix before final linking.
        run(compile_cmd)
        obj_symbols = parse_nm(run([tool_prefix + "nm", "--defined-only", str(obj)]))
        init_sym, update_sym, draw_sym = detect_entries(obj_symbols, entry_prefix)

        link_objects = [str(obj)]
        linker_scripts = ["-Wl,-T," + str(linker_ld)]
        entry_init_sym = init_sym
        entry_update_sym = update_sym
        entry_draw_sym = draw_sym
        if portable:
            write_portable_stubs(stubs_s, init_sym, update_sym, draw_sym)
            run([
                tool_prefix + "gcc",
                "-mcmodel=medany",
                "-msmall-data-limit=0",
                "-march=" + march,
                "-mabi=" + mabi,
                "-x", "assembler-with-cpp",
                "-c", str(stubs_s),
                "-o", str(stubs_o),
            ])
            link_objects.append(str(stubs_o))
            entry_init_sym = "prg32_entry_init"
            entry_update_sym = "prg32_entry_update"
            entry_draw_sym = "prg32_entry_draw"
        else:
            write_imports(imports_ld, imports)
            linker_scripts.append("-Wl,-T," + str(imports_ld))
            
        write_linker(linker_ld, load_addr, entry_init_sym)
        run([
            tool_prefix + "gcc",
            "-nostdlib",
            "-march=" + march,
            "-mabi=" + mabi,
            *(["-mcmodel=medany", "-msmall-data-limit=0"] if portable else []),
            "-Wl,--no-relax",
            *linker_scripts,
            "-Wl,-Map," + str(tmp / "game.map"),
            *link_objects,
            "-o", str(elf),
        ])
        linked_symbols = parse_nm(run([tool_prefix + "nm", "--defined-only", str(elf)]))
        run([tool_prefix + "objcopy", "-O", "binary", str(elf), str(raw)])

        code = raw.read_bytes()
        audio_block_data = b""
        flags = 0
        if audio_block:
            audio_block_data = Path(audio_block).read_bytes()
            if len(audio_block_data) < 40 or audio_block_data[:4] != AUDIO_BLOCK_MAGIC:
                raise SystemExit(
                    f"{audio_block} is not a PRG32 AUDIO block"
                )
            block_size = struct.unpack_from("<I", audio_block_data, 36)[0]
            if block_size != len(audio_block_data):
                raise SystemExit(
                    f"{audio_block} declares {block_size} bytes "
                    f"but file has {len(audio_block_data)}"
                )
            flags |= PRG32_CART_FLAG_AUDIO_BLOCK
            
        if multiplayer:
            flags |= PRG32_CART_FLAG_MULTIPLAYER
            req_features |= FEATURE_BITS["multiplayer"]
        if portable:
            flags |= PRG32_CART_FLAG_ABI_TABLE
            
        start = linked_symbols["__cart_start"]
        end = linked_symbols["__cart_end"]
        mem_size = end - start
        if mem_size <= 0 or mem_size > ram_size:
            raise SystemExit(f"cartridge needs {mem_size} bytes, runtime has {ram_size}")
        if len(code) > mem_size:
            raise SystemExit("internal error: binary is larger than cartridge memory")

        entries = {
            "init": linked_symbols[entry_init_sym] - load_addr,
            "update": linked_symbols[entry_update_sym] - load_addr,
            "draw": linked_symbols[entry_draw_sym] - load_addr,
        }
        crc = binascii.crc32(code) & 0xffffffff
        header_struct = CART_HEADER_V2 if portable else CART_HEADER
        header_values = [
            CART_MAGIC,
            CART_ABI_MAJOR,
            CART_ABI_MINOR,
            header_struct.size,
            flags,
            load_addr,
            len(code),
            mem_size,
            entries["init"],
            entries["update"],
            entries["draw"],
            crc,
            name_bytes + b"\0" * (32 - len(name_bytes)),
        ]
        if portable:
            header_values.extend([
                ABI_HASH,
                req_features,
                opt_features,
                0,
                0,
                0,
                PRG32_IMPORT_MODEL_ABI_TABLE,
            ])
        header = header_struct.pack(*header_values)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_bytes(header + code + audio_block_data)


    out_path = Path(out)
    if not out_path.exists() or out_path.stat().st_size == 0:
        die(f"Cartridge build failed: {out_path} was not created or is empty")
    log_ok(f"built {out} name={name} load=0x{load_addr:08x}")
    log_info(f"code={len(code)} mem={mem_size} audio={len(audio_block_data)}")

def build_cartridge_cli(args: argparse.Namespace) -> None:
    """
    You can either specify an architecture or override single options (firmware_elf).
    This is to simplify common commands.
    """

    architecture = args.architecture
    portable = args.portable or (not args.firmware_elf and not getattr(args, "legacy_absolute_imports", False))

    if portable:
        firmware_elf = args.firmware_elf
        build_dir = args.build_dir
    else:
        firmware_elf = args.firmware_elf or (TARGET_DEFAULTS[architecture]["firmware_elf"] if architecture else None)
        build_dir = args.build_dir or (TARGET_DEFAULTS[architecture]["build_dir"] if architecture else None)
        if not firmware_elf:
            die("Must specify --architecture or --firmware-elf when not building portable cartridges")
            
    log_info(f"Building for architecture: {architecture}")
    log_info(f"Using Firmware ELF: {firmware_elf}")
    log_info(f"Portable: {portable}")
    

    if not Path(args.source).exists():
        die(f"Missing game source: {args.source}")
    filename = args.out
    game_name = filename.rsplit('.', 1)[0]
    log_info(f"Building cartridge: {game_name} (Prefix: {args.entry_prefix})")
    
    env = os.environ.copy()
    if build_dir:
        env['CPATH'] = f"{build_dir}/config:{build_dir}:{env.get('CPATH','')}"

    build_cartridge_core(source=args.source,
                         out=args.out,
                         entry_prefix=args.entry_prefix,
                         tool_prefix=args.tool_prefix,
                         march=args.march,
                         mabi=args.mabi,
                         portable=portable,
                         legacy_absolute_imports=args.legacy_absolute_imports,
                         required_features=args.required_feature,
                         optional_features=args.optional_feature,
                         multiplayer=args.multiplayer,
                         audio_block=args.audio_block,
                         runtime_url=args.runtime_url,
                         firmware_elf=firmware_elf,
                         name=args.name
                         )
